In [1]:
import numpy as np

In [4]:
## lets have data for predicting 1 or 0
## 0 belongs to pnemonia and 1 belongs to normal
## we are experimenting class imbalance problem
y_true=np.array([[1],
                 [1],
                 [1],
                 [0]])
y_true

array([[1],
       [1],
       [1],
       [0]])

In [11]:
# considering one model 
y_pred_1=np.ones(y_true.shape)*0.9
# another
y_pred_2=np.ones(y_true.shape)*0.1

In [12]:
y_pred_1

array([[0.9],
       [0.9],
       [0.9],
       [0.9]])

In [13]:
y_pred_2

array([[0.1],
       [0.1],
       [0.1],
       [0.1]])

In [15]:
## 
loss_reg_1 = -1 * np.sum(y_true * np.log(y_pred_1)) -1 * np.sum((1 - y_true) * np.log(1 - y_pred_1))
print(f"loss_reg_1: {loss_reg_1:.4f}")

loss_reg_1: 2.6187


In [16]:
loss_reg_2 = -1 * np.sum(y_true * np.log(y_pred_2)) + \
                -1 * np.sum((1 - y_true) * np.log(1 - y_pred_2))
print(f"loss_reg_2: {loss_reg_2:.4f}")

loss_reg_2: 7.0131


In [17]:
print(f"When the model 1 always predicts 0.9, the regular loss is {loss_reg_1:.4f}")
print(f"When the model 2 always predicts 0.1, the regular loss is {loss_reg_2:.4f}")

When the model 1 always predicts 0.9, the regular loss is 2.6187
When the model 2 always predicts 0.1, the regular loss is 7.0131


In [18]:
# calculate the positive weight as the fraction of negative labels
w_p = 1/4

# calculate the negative weight as the fraction of positive labels
w_n = 3/4

print(f"positive weight w_p: {w_p}")
print(f"negative weight w_n {w_n}")

positive weight w_p: 0.25
negative weight w_n 0.75


In [19]:
# Calculate and print out the first term in the loss function, which we are calling 'loss_pos'
loss_1_pos = -1 * np.sum(w_p * y_true * np.log(y_pred_1 ))
print(f"loss_1_pos: {loss_1_pos:.4f}")

loss_1_pos: 0.0790


In [20]:
# Calculate and print out the second term in the loss function, which we're calling 'loss_neg'
loss_1_neg = -1 * np.sum(w_n * (1 - y_true) * np.log(1 - y_pred_1 ))
print(f"loss_1_neg: {loss_1_neg:.4f}")

loss_1_neg: 1.7269


In [21]:
# Sum positive and negative losses to calculate total loss
loss_1 = loss_1_pos + loss_1_neg
print(f"loss_1: {loss_1:.4f}")

loss_1: 1.8060
